[package]
name = "ossa-crdt"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im = {version = "*", features = ["serde"] }
serde = "*"
typeable = {path="../typeable"}
