[package]
name = "ossa-core"
version = "0.0.1"
edition = "2021"
license = "MPL-2.0"
description = "Rust implementation of the Ossa Protocol."
homepage = "https://github.com/jprider63/ossa"
repository = "https://github.com/jprider63/ossa"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-recursion = { workspace = true }
async-session-types = { workspace = true }
bitvec = { workspace = true }
bs58 = { workspace = true }
bytes = { workspace = true }
ed25519-dalek = { workspace = true }
daggy = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
hints-bls12381 = { workspace = true }
itertools = { workspace = true }
ossa-crdt = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
replace_with = { workspace = true }
serde = { workspace = true }
serde_cbor = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
void = { workspace = true }
ossa-typeable = { workspace = true, features=["serde", "ed25519-dalek"] }
portmapper = { workspace = true }

[dev-dependencies]
petgraph = "0.8.2"
