[package]
name = "ossa-dioxus"
version = "0.0.1"
edition = "2024"
license = "MPL-2.0"
description = "Dioxus integration for the Ossa Protocol implementation, `ossa-core`."
homepage = "https://github.com/jprider63/ossa"
repository = "https://github.com/jprider63/ossa"

[dependencies]
dioxus = { workspace = true }
dioxus-desktop = { workspace = true }
ossa-core = { workspace = true }
ossa-crdt = { workspace = true }
tracing = { workspace = true }

